angular.module('app', [

    /**
     * router module
     * -------------
     *
     * Defined in `src/libs/router.js`
     */

    'router',

    /**
     * app.partials module
     * -------------------
     *
     * Generated by the build system through the `html2js` task
     *
     * Contains all the partials compiled to a single js adding them to
     * the angular's template cache
     */

    'app.partials',

    /**
     * app.controllers module
     * ----------------------
     *
     * Defined in `src/app/controllers.js`
     */
    
    'app.controllers'
]);
