angular.module('app', [

	/**
	 * partials module
	 * ---------------
	 *
	 * Generated by the build system through the `html2js` task
	 *
	 * Contains all the partials compiled to a single js adding them to
	 * the angular's template cache
	 */
	'partials',

	/**
	 * routes module
	 * -------------
	 *
	 * Defined in `routes.js`
	 *
	 * Contains all the application routes binding URLs to HTML views
	 *
	 * Controllers are declared in the HTML. That way, a single view can use
	 * multiple controllers in sereral parts
	 */
	'routes'
]);